version: '3.3'
services:
  db:
    container_name: s3-backup-db
    build:
        context: ./
        dockerfile: Dockerfile
    volumes:
      - "./.db:/var/lib/mysql"
      - "./:/var/app"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
